'use client';

import { ArrowLeft, ArrowUpRight, BadgeCheck, Heart, MessageCircle, Music2, Play, Radio, Share2, Sparkles, Users, Volume2, Waves } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useGame } from '@/lib/game';

const profiles: Record<string, { name: string; handle: string; mark: string; color: string; kind: string }> = {
  'apple-music': { name: 'Apple Music', handle: 'Candelar', mark: '♫', color: 'linear-gradient(145deg,#f0788b,#92304f)', kind: 'apple' },
  soundcloud: { name: 'SoundCloud', handle: 'candelar', mark: '☁', color: 'linear-gradient(145deg,#ffab4d,#d95120)', kind: 'cloud' },
  audiomack: { name: 'Audiomack', handle: 'Candelar', mark: 'a', color: 'linear-gradient(145deg,#ffca56,#d27a1f)', kind: 'tape' },
  threads: { name: 'Threads', handle: '@candelar', mark: '@', color: '#29262b', kind: 'thread' },
  facebook: { name: 'Facebook', handle: 'Candelar Music', mark: 'f', color: 'linear-gradient(145deg,#5f90ea,#3656a7)', kind: 'facebook' },
  twitch: { name: 'Twitch', handle: 'candelarlive', mark: '▣', color: 'linear-gradient(145deg,#a47bed,#5b409d)', kind: 'twitch' },
  snapchat: { name: 'Snapchat', handle: 'candelar', mark: '◉', color: 'linear-gradient(145deg,#ffe658,#e9bb2b)', kind: 'snap' },
};

export default function SocialOtherPlatform({ slug }: { slug: string }) {
  const game = useGame();
  const [composer, setComposer] = useState(false);
  const [draft, setDraft] = useState('');
  const [liked, setLiked] = useState(false);
  const profile = profiles[slug];
  useEffect(() => { void useGame.persist.rehydrate(); }, []);
  if (!profile) return <main className="platform-page"><header className="site-header"><Link href="/social" className="site-logo">TREBLR</Link></header><section className="platform-layout"><h1>This part of your online life is still quiet.</h1><Link href="/social" className="pill-button">BACK TO SOCIAL</Link></section></main>;
  const publish = (text?: string) => { const copy = text ?? draft.trim(); if (!copy) return; game.publishPost(profile.name, copy); setDraft(''); setComposer(false); };
  const composerBox = <div className="quote-note" style={{ marginTop: 17 }}><div className="eyebrow">A MOMENT FOR {profile.name.toUpperCase()}</div><textarea className="field" rows={3} value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Something you want to put into the world…" style={{ marginTop: 9 }}/><div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 9 }}><button className="pill-button orange" onClick={() => publish()}>SHARE A MOMENT</button></div></div>;
  const artwork = (index: number) => ['linear-gradient(145deg,#34233d,#dc8262)','linear-gradient(145deg,#27434b,#c98f64)','linear-gradient(145deg,#552f43,#e3a264)','linear-gradient(145deg,#253241,#a65f53)'][index % 4];
  return <main className={`platform-page extra-${slug}`} style={profile.kind === 'cloud' ? { background: '#191918', color: '#f8f5ef' } : profile.kind === 'tape' ? { background: '#191816', color: '#fbf7ed' } : profile.kind === 'twitch' ? { background: '#18141e', color: '#faf7ff' } : profile.kind === 'snap' ? { background: '#faf8ef' } : undefined}>
    <header className="site-header"><Link href="/" className="site-logo">TREBLR</Link><Link href="/social" className="back-link"><ArrowLeft size={13}/> ALL SOCIAL WORLDS</Link></header>
    <section className="platform-layout">
      {profile.kind === 'apple' && <><div className="extra-brand-line" style={{ color: '#ed617e' }}><span className="extra-mark" style={{ background: profile.color }}>{profile.mark}</span> APPLE MUSIC · ARTIST PROFILE</div><div className="extra-apple-hero"><div className="extra-apple-cover" style={{ background: artwork(0) }}>C.</div><div><div className="eyebrow" style={{ color: '#af6b67' }}>AFRO-FUSION · {game.currentCity.toUpperCase()}</div><h1>{profile.handle} <BadgeCheck size={16} color="#c35b70" fill="#f6dfe4"/></h1><p>{(game.monthlyListeners * .64 / 1000).toFixed(0)}K monthly listeners · Listener-loved</p><button className="pill-button orange" onClick={() => publish('A new chapter, a familiar voice. Find me on Apple Music.')}>SHARE YOUR ARTIST PAGE <ArrowUpRight size={12}/></button></div></div><div className="extra-two-column"><section className="extra-white-pane"><div className="eyebrow">LATEST RELEASES</div>{game.songs.map((song, i) => <div className="stream-row extra-light-row" key={song.id}><div className="extra-cover-small" style={{ background: artwork(i) }}/><span>{song.title}<br/><small>{song.genre} · Single</small></span><small>{song.status === 'RELEASED' ? `${(song.streams / 1000).toFixed(0)}K plays` : 'DEMO'}</small>{song.status !== 'RELEASED' && <button className="pill-button small" onClick={() => game.releaseSong(song.id)}>RELEASE</button>}</div>)}</section><section className="extra-white-pane extra-city-pane"><div className="eyebrow">LISTENERS LOVE YOU IN</div><h2>{game.currentCity}</h2><p>Your sound is finding new ears across the city.</p><div className="extra-world-lines">{['Lagos','London','Accra','Toronto'].map((city, i) => <div key={city}><span>{city}</span><i style={{ width: `${82 - i * 13}%` }}/><small>{[82,66,53,37][i]}%</small></div>)}</div></section></div></>}
      {profile.kind === 'cloud' && <><div className="cloud-toolbar"><span className="extra-mark" style={{ background: profile.color }}>{profile.mark}</span><b>SOUNDCLOUD</b><span className="cloud-search">Search for sounds, artists, podcasts</span><span style={{ color: '#ff963e', font: '600 9px var(--display)' }}>ARTIST PAGE</span></div><div className="cloud-cover"><div className="cloud-disc">C</div><div><div className="eyebrow" style={{ color: '#ffb06b' }}>SOUNDCLOUD · {profile.handle}</div><h1>Candelar</h1><p>Afro-fusion sketches, bedroom takes & finished songs.</p><div className="cloud-facts"><span><Play size={13}/> 1.8M total plays</span><span><Users size={13}/> {Math.round(game.fans / 1000)}K listeners</span><span><Heart size={13}/> 42K hearts</span></div></div></div><div className="cloud-actions"><button className="cloud-play" onClick={() => setLiked(!liked)}><Play size={13} fill="currentColor"/> PLAY LATEST</button><button className="cloud-follow" onClick={() => publish('New room, same feeling. SoundCloud has the late-night sketches.')}>REPOST A MOMENT</button></div><div className="cloud-wave-row"><div className="eyebrow">YOUR TRACKS · RECENT PLAYS</div>{game.songs.map((song, i) => <div className="cloud-track" key={song.id}><button className="cloud-track-play" onClick={() => setLiked(!liked)}><Play size={13}/></button><div className="cloud-track-art" style={{ background: artwork(i) }}/><div style={{ flex: 1 }}><b>{song.title}</b><small>{song.genre} · {song.status.toLowerCase()}</small><div className="wave-bars">{Array.from({ length: 60 }, (_, n) => <i key={n} style={{ height: `${10 + ((n * 17 + i * 23) % 33)}px` }}/>)}</div></div><span>{song.streams ? `${(song.streams / 1000).toFixed(0)}K` : 'DEMO'}</span></div>)}</div></>}
      {profile.kind === 'tape' && <><div className="audiomack-header"><div className="extra-mark" style={{ background: profile.color }}>{profile.mark}</div><div><div className="eyebrow" style={{ color: '#f6b943' }}>AUDIOMACK · TRENDING ARTIST</div><h1>Candelar</h1><p>New wave · Afro-fusion · Lagos and everywhere</p></div><button className="pill-button orange" onClick={() => publish('The road keeps opening up. Thank you for listening on Audiomack.')}>FOLLOW</button></div><div className="tape-metrics"><div><b>{Math.round(game.monthlyListeners * .31 / 1000)}K</b><span>MONTHLY LISTENERS</span></div><div><b>{Math.round(game.fans * .3 / 1000)}K</b><span>SUPPORTERS</span></div><div><b>16</b><span>PLAYLIST ADDS</span></div></div><div className="eyebrow" style={{ color: '#f0b540', margin: '24px 0 10px' }}>MIXTAPES · EPs · SINGLES</div><div className="tape-grid">{game.songs.slice(0, 4).map((song, i) => <button className="tape-tile" key={song.id} onClick={() => song.status !== 'RELEASED' && game.releaseSong(song.id)} style={{ border: 0, textAlign: 'left' }}><div className="tape-art" style={{ background: artwork(i) }}><Music2 size={25}/><span>CANDELAR</span></div><b>{song.title}</b><small>{song.status === 'RELEASED' ? 'EP · 2026' : 'TAP TO RELEASE'}</small></button>)}</div></>}
      {profile.kind === 'thread' && <><div className="thread-heading"><span className="extra-mark" style={{ background: profile.color }}>{profile.mark}</span><div><div className="eyebrow">THREADS · WHAT’S HAPPENING</div><h1>{profile.handle}</h1><p>{Math.round(game.fans / 1000)}K followers · Artist, always becoming</p></div><button className="pill-button" onClick={() => setComposer(!composer)}>NEW THREAD</button></div><div className="thread-prompt"><span className="thread-avatar">C</span><button onClick={() => setComposer(true)}>Start a thread…<ArrowUpRight size={14}/></button></div>{composer && <div className="quote-note"><textarea className="field" value={draft} onChange={(e) => setDraft(e.target.value)} rows={3} placeholder="Something you’ve been thinking about…"/><button className="pill-button orange" style={{ marginTop: 9 }} onClick={() => publish()}>POST THREAD</button></div>}<div className="thread-feed">{[...game.posts.filter((p) => p.platform === 'Threads'), { platform: 'Threads', text: 'some songs are just conversations you finally learned how to finish.', likes: 8450, time: '3h' }, { platform: 'Threads', text: 'Teo says the second verse needs less explaining. he’s probably right again.', likes: 3890, time: '1d' }].map((p, i) => <article className="thread-post" key={`${p.text}-${i}`}><span className="thread-avatar">C</span><div><div className="thread-handle">candelar <small>{p.time}</small><span>···</span></div><p>{p.text}</p><div className="thread-reactions"><button onClick={() => setLiked(!liked)}><Heart size={13} fill={liked ? '#c74f58' : 'none'}/> {Math.round(p.likes / 100) / 10}K</button><span><MessageCircle size={13}/> 84</span><span><Share2 size={13}/> 27</span></div></div></article>)}</div></>}
      {profile.kind === 'facebook' && <><div className="fb-cover"><div className="fb-cover-copy"><div className="eyebrow">MUSIC · ARTIST</div><h1>The songs and<br/>the people in them.</h1></div></div><div className="fb-identity"><span className="fb-avatar">C.</span><div><h2>Candelar Music <BadgeCheck size={15} color="#3e77d0"/></h2><p>{Math.round(game.fans / 1000)}K followers · Musician/band · {game.currentCity}</p></div><button className="pill-button" onClick={() => publish('Following wherever the music takes us. Thanks for being here.')}>FOLLOW PAGE</button></div><div className="fb-tabs">POSTS · ABOUT · MUSIC · PHOTOS · EVENTS</div><div className="fb-columns"><aside className="fb-about"><div className="eyebrow">ABOUT</div><p>Afro-fusion for the long way home.</p><span>From {game.artist.origin} · Lives in {game.currentCity}</span><div className="quote-note">Upcoming · Lagos Music Festival<br/>October 12 · Golden-hour stage</div></aside><div>{[...game.posts.filter((p) => p.platform === 'Facebook'), { platform: 'Facebook', text: 'Thank you for making the first 100 days of this record feel like a long, warm night.', likes: 1940, time: '5h' }].map((p, i) => <article className="fb-post" key={`${p.text}-${i}`}><b>Candelar Music</b><small>{p.time} · followers</small><p>{p.text}</p><div className="post-meta"><span><Heart size={13}/> {p.likes.toLocaleString()}</span><span><MessageCircle size={13}/> 34 comments</span></div></article>)}{composer && composerBox}</div></div></>}
      {profile.kind === 'twitch' && <><div className="twitch-header"><span className="extra-mark" style={{ background: profile.color }}>{profile.mark}</span><div><div className="eyebrow" style={{ color: '#c7adff' }}>TWITCH · MUSIC & MORE</div><h1>candelarlive</h1><p>Late-night writing sessions, live rehearsals, and an open chat.</p></div><button className="twitch-follow" onClick={() => publish('We’ll be live after the next session. Bring your ideas.')}>FOLLOW</button></div><div className="twitch-stage"><div className="twitch-stage-light"/><div className="twitch-live-pill"><span/> OFFLINE · BACK AFTER THE SESSION</div><div className="twitch-stage-center"><Radio size={39}/><b>Next up: building a song, live.</b><small>Stream night · {game.currentCity} · {game.relationships.length} friends said they’ll join</small><button className="twitch-remind" onClick={() => publish('Turn on notifications for the next live writing session.')}>NOTIFY ME</button></div></div><div className="twitch-panels"><article><div className="eyebrow">ABOUT CANDELAR</div><p>Sometimes the best part of the song is the room it was made in. Come sit in.</p></article><article><div className="eyebrow">RECENTLY LIVE</div><b>Never Met You · live arrangement</b><small>1.2K viewers · 4 days ago</small></article><article><div className="eyebrow">THE COMMUNITY</div><b>{Math.round(game.fans / 1000)}K</b><small>people listening along</small></article></div></>}
      {profile.kind === 'snap' && <><div className="snap-top"><div className="snap-ghost">◉</div><div><div className="eyebrow">SNAPCHAT · RIGHT NOW</div><h1>{profile.handle}</h1><p>Story · {game.currentCity} · 1h ago</p></div><button className="snap-camera" onClick={() => publish('Little snapshot from the studio tonight 📸')}>OPEN CAMERA</button></div><div className="snap-story-row">{['Your night','Studio','The crew','On tour','Old snaps'].map((story, i) => <button className="snap-story" key={story} onClick={() => publish(`A snap from ${story.toLowerCase()} 👻`)}><span style={{ background: artwork(i), borderColor: i === 0 ? '#e6c323' : '#ede9df' }}>{i === 0 ? '+' : ['S','♪','C','✈'][i - 1]}</span><small>{story}</small></button>)}</div><div className="snap-memory" style={{ background: artwork(2) }}><div className="snap-memory-top"><span>CANDELAR · 01:08 AM</span><span>24h STORY</span></div><div className="snap-memory-copy"><div className="eyebrow">FROM THE STUDIO</div><h2>somewhere<br/>between the<br/>first take & the truth</h2><button onClick={() => setLiked(!liked)}><Heart fill={liked ? '#f66c68' : 'none'} size={15}/> {liked ? 'sent you a little love' : 'tap to react'}</button></div></div>{composer && composerBox}</>}
    </section>
  </main>;
}
